### ISSUE TITLE
calc_model function not in calculation_functions.py

### ISSUE THREAD

**Issue by shalverson** [tamarervin/SolAster#7]
https://github.com/tamarervin/SolAster/blob/c6fccf47ccf046dfe9ff1575644facfd01c9e68c/SolAster/tools/rvs.py#L27

Looks like the notebooks are expecting the calc_model function to be in calculation_functions.py, but it's in rvs.py?

<img width="837" alt="Screen Shot 2022-01-27 at 11 37 25 AM" src="https://user-images.githubusercontent.com/2415196/151431176-102beacf-2666-41c5-80c5-7fe9ee169846.png">

**Comment by tamarervin** [comment]
Fixed!
